### ISSUE TITLE
Niche Feature Request: Add the ability to burn an image to a disc

### ISSUE THREAD

**Issue by AE720** [rescuezilla/rescuezilla#183] opened 2021-02-01 14:00 UTC
Obviously this should be the lowest priority but thought it was something that might be interesting to implement/keep a note of. I know Redo did a better job at compressing the sizes of images in my experience but with optical media such as blu-ray I thought it might be nice to be able to natively burn an image to a disc or to read from one. I know flash storage is cheap but the thought of being able to burn a linux setup I have on something more longterm is a bit more appealing to me. Perhaps a way to split to multiple discs and have it be able to detect that would be nice but again, I don't want any resources towards this that would take away from anything more important but just an idea I know that I would personally utilize. If it never fully comes to fruition I would be alright with that too.

**Comment by shasheene** [comment] 2021-02-01 22:45
Duplicate of task #9 ("Burning backups to DVD"). Thanks for the "vote", I wasn't even sure anybody would be interested in such a feature.

Yeah definitely a low priority for integrating into Rescuezilla GUI, but **adding a disk burning tool is something that can easily be done in the short term.** I'm open to application suggestions.

I'm surprised that legacy Redo Backup (which used single-threaded 'gzip') had better compression ratios than Rescuezilla, as I have found the default settings on the multi-threaded 'pigz' tool to have better compression ratios (and be _much_ faster). Regardless, Rescuezilla v2.2 will [add ability to select compression format (such as zstd/zstandard), compression levels, etc (task #170)](https://github.com/rescuezilla/rescuezilla/issues/170), which will also add a slider that can improve compression ratio (at the expense of backup duration). If you want much better compression ratios (with similarly fast decompression), I recommend switching to Zstandard compression. The current split size is 4GB, so I will try and provide the ability to customize this to allow eg, 700MB (CD), 4.7GB (DVD), 25GB (Blu-Ray disks size?) etc.

**Closed by shasheene** 2021-02-01 22:45 UTC
