### ISSUE TITLE
cannot restore backup

### ISSUE THREAD

**Issue by dduran1210** [rescuezilla/rescuezilla#108] opened 2020-07-05 14:36 UTC
I created a backup with no problem.  However, I cannot RESTORE this same backup.  It finds the backup ok....but 
for destination.....it does NOT show my linuxmint20 partition..
[rescuezilla.log.20200704T213559.txt](https://github.com/rescuezilla/rescuezilla/files/4875056/rescuezilla.log.20200704T213559.txt)
[rescuezilla.log.20200704T213559.txt](https://github.com/rescuezilla/rescuezilla/files/4875057/rescuezilla.log.20200704T213559.txt)

**Comment by shasheene** [comment] 2020-07-06 01:19
Hi @dduran1210,

Please try and keep support requests on the [Rescuezilla support forum](https://sourceforge.net/p/rescuezilla/discussion/) (as a new forum topic as relevant), because the GitHub issues is mainly for development tasks. But for now this is OK.

From what I can tell from your log files, I suspect Rescuezilla v1.0.6.1 **is working correctly**. On "Step 3: Select Drive to Restore", does the menu show you a list of 3 drives?

> Drive 1 (WDC WD20EZRZ-00Z): (CLONE CEE, 598.34 GB ntfs) (CLONE DEE, 598.34 GB ntfs) (swap 1.86 GB)...
> Drive 2 (WDC WD10EZEX-00W): (System Reserved, 100.00 MB ntfs) (CEE-NOW, 396.29 GB ntfs) (DEE-NOW,...
> Drive 3 (easystore 2625): (ACRONIS HM, 1.99 GB vfat) (100.00 MB unknown) (FLASH DRIV- 2NDAR, 297.03 GB)...

Is your Linux Mint 20 partition labelled "CINNAMON" and 54.19 GB in size? If so, the correct menu item to select is Drive 1. I think the issue here is that Rescuezilla's menu can't list all the partitions in its menu.

By the way, you mentioned in your other Sourceforge support [forum topic](https://sourceforge.net/p/rescuezilla/discussion/support/thread/0acb85dc8a/#c806/4cb5/ae55/f5f1/1650) that you are testing Timeshift and luckyBackup. Please be aware that Rescuezilla currently overwrites the entire partition table when it does a restore. This is not an issue if you have **not** added or resized any partitions since your last backup (eg, you have not installed a new operating system alongside your existing ones, or used the GParted tool to resize your partitions). This limitation makes Rescuezilla suitable for the backup/restore of whole hard drives, but less suitable for individual partition backup/restore. Rescuezilla can still be used for the backup/restore of individual partitions (like your Linux Mint partition), but the enduser must not have modified the partition table by resizing partitions or installing new operating systems since last backup. Rescuezilla **can** still be used in the way you want to use it, but it's something to be aware of. I am improving upon this limitation for the next version of Rescuezilla (v1.0.7 which will be released in a few months).

**Comment by shasheene** [comment] 2020-07-08 00:07
To summarize, after discussion on the 
"[Setting Time on Rescuezilla](https://sourceforge.net/p/rescuezilla/discussion/support/thread/0acb85dc8a/)" and "[RESTORING RESCUEZILLA](https://sourceforge.net/p/rescuezilla/discussion/support/thread/ffc28a3396/)" support forum threads, Rescuezilla v1.0.6.1 is working as expected. On "Step 3: Select Drive to Restore", the menu is correctly displaying the enduser's 3 drives.

The user is trying to restore partition 7 of Drive 1 with Rescuezilla v1.0.6.1. It's the fact it's not shown on the restore screen (due to the short one line menu) that leads to poor usability. In other words, this is an issue around usability and adding an improved interface with the ability to restore partitions individually. Rescuezilla v1.0.6.1 is not well suited to backup/restore of individual partitions (already captured as task #46).

The root cause of this issue will be resolved in Rescuezilla v1.0.7. I am closing this GitHub issue as "INVALID" because task #46 is already improving this functionality. Rescuezilla v1.0.7 will be release in the September/October 2020 timeframe.

**Closed by shasheene** 2020-07-08 00:07 UTC
