### ISSUE TITLE
Rescuezilla 1.0.5 Requires me to Login to Ubuntu

### ISSUE THREAD

**Issue by FluorescentGreen5** [rescuezilla/rescuezilla#25] opened 2019-11-27 14:17 UTC
After letting it deal with an "undefined video mode" on its own, it asks me to login to Ubuntu via a text screen.

I loaded the ISO onto my thumbdrive using a very recent release of Legacy YUMI from Windows 7 and am trying to boot a (BIOS based) netbook with 1GB of RAM from it.

**Comment by shasheene** [comment] 2019-11-27 22:05
Hi, thank you for the bug report. 

I haven't tried creating an bootable USB stick using multiboot tools like YUMI or tools like unetbootin, but please do the following:

This issue happened very regularly on v1.0.4 but has been fixed on v1.0.5 -- at least on all systems I have tested against. Confirm your ISO matches a checksum and is indeed v1.0.5:
```
Checksums
sha256sum:
b67900f94b0cd2886b1cc3b56ee71cbe33dc6ccda55d8248a257faa245cd7e87 redobackup-livecd-1.0.5.iso

sha1sum: 8a403ad78ab258a76207525c17fd2002a746aec1 redobackup-livecd-1.0.5.iso

md5sum: 30dc2b177ff10a3c619c6d9a389e81b1 redobackup-livecd-1.0.5.iso
```

Please try selecting safemode from the menu and selecting a fixed video mode which avoids using the standard Kernel Mode Setting approach that doesn't work with some hardware.

If your problem persists, login to the console session with username 'ubuntu' and an empty password. Then try `sudo systemctl restart slim`. If it still doesn't work, the output of the system journal and Xorg server are important for further debugging.

**Comment by FluorescentGreen5** [comment] 2019-11-28 00:58
I've used the original 2012 version 1.0.4 ISO before and never had this login issue before (although I used an older version of YUMI to load the ISO).

Here are the checksums I calculated, they seem to match the ones you provied:
```
MD5:    30DC2B177FF10A3C619C6D9A389E81B1
SHA-1:  8A403AD78AB258A76207525C17FD2002A746AEC1
SHA256: B67900F94B0CD2886B1CC3B56EE71CBE33DC6CCDA55D8248A257FAA245CD7E87

SHA512: 4C236226E8EB3C3C68A4BB0AB7629AEC4F5B7EA0229BD22CB48DAAC6A36F266D
        1CFBC2230C9C21F721E39182C8621949F4A1434180666E2345AD8816E165F2C8
```

In the meantime, I will try the workarounds you suggested and follow up in an edit. Thank you for your help.

**Comment by shasheene** [comment] 2019-11-28 01:34
OK, I am glad Safe Mode worked for you!

Once you're in the graphical environment! I'm not sure what's going on with the deep fried logo. Can you please post your hardware information?

Once booted into the graphical environment you may be able to change the resolution using the right-click menu (there may be a limited number of options).

More importantly, please note: Safe Mode uses the 'toram' kernel parameter loads the entire ISO image into RAM (which allows the USB stick to be removed without affecting the session). This is sufficient for backup/restore on systems with 1GB RAM, but it's not ideal -- especially if you want to use the web browser. 

Given that leaving the USB stick inserted is not an issue, you can press the tab key when highlighting the 'Safe Mode' menu item. and remove the 'toram' kernel parameter. If anyone reading this comment has a machine with less than 1GB RAM, I recommend the text-based application Clonezilla, as the minimum system requirements is 196 MB.

**Comment by FluorescentGreen5** [comment] 2019-11-28 05:36
Here's a picture of the deep fried Redo logos. I edited out some of the screen reflections but made below it while making sure not to modify the actual focus of the image.
![image](https://user-images.githubusercontent.com/37255338/69779285-96a3c480-11fb-11ea-8c55-75daddccf39b.png)

When selecting a video mode, I picked the last one on the list and once it finished booting up, it seemed like it was already using the native screen resolution.

About Redo V.S. Clonezilla, I felt Clonezilla was overkill and overcomplicated for my current use case (since all I'm trying to do it make an image of my old netbook before wiping it and converting it to a server). It's the main reason I settled with Redo Backup. I might try again with learning Clonezilla sometime in the future, but I'm glad someone has picked up Redo and continued working on it 7 years later as it is a good disk imaging utility.

**Comment by AlphaBootis** [comment] 2020-01-23 19:09
Currently dealing with the same issue on a HPCompaq DC7800SFF. Reproducable over multiple systems (of same make and model). Same stick boots fine on different hardware.
Safe mode **does** boot, but it completely ignores anything I do resolution wise. It always boots to 640x480.

> If your problem persists, login to the console session with username 'ubuntu' and an empty password. Then try sudo systemctl restart slim. If it still doesn't work, the output of the system journal and Xorg server are important for further debugging.

The screen flickers five times, as it does when trying to boot normally, but nothing happens.
How would I go about getting you the needed log output. Is there a way to SSH into a clonezilla session or something? Otherwise I will be taking actual pictures of a screen.

**Comment by shasheene** [comment] 2020-01-24 01:45
> Currently dealing with the same issue on a HPCompaq DC7800SFF. Reproducable over multiple systems (of same make and model). Same stick boots fine on different hardware.
> Safe mode does boot, but it completely ignores anything I do resolution wise. It always boots to 640x480.

Rescuezilla safe mode launches with the generic VESA driver. Not all graphics chips support every resolution using the generic VESA driver. I don't know the specifications of your graphics chip.

Booting outside safe mode automatically tries to use the maximum display resolution. On machine with limited video memory (such as VirtualBox) this causes the graphical session to fail on higher resolution displays, unless the video memory is increased beyond the default 28MB.

You may already know this, but there are two ways to modify the screen resolution in safe mode. The first is by pressing <ENTER> when it prompts during boot up. The second is by right clicking on the desktop wallpaper and selecting "Display resolution and layout" to launch the `arandr` utility. You may have the option to select a more bearable 800x600 or even 1024x768.

> Old redo stick boots just fine on this same machine.

This is interesting. Does booting recent Ubuntu environments like Lubuntu 19.04 live distribution also fail to start the graphical session like Rescuezilla v1.0.5?

> The screen flickers five times, as it does when trying to boot normally, but nothing happens.

The screen flickering SLiM login manager background service (added in v1.0.5) attempting to start the graphical session but failing. It gives up after a number of attempts.

> How would I go about getting you the needed log output. Is there a way to SSH into a clonezilla session or something? Otherwise I will be taking actual pictures of a screen.

For security reasons, there is no SSH server installed. However, an SSH client is installed. You can run `sudo apt-get update && sudo apt-get install openssh-server` to install packages into the non-persistent RAM overlay. An alternative approach is to insert and mount a USB stick. The log files from `/var/log/Xorg*` and other log files like the kernel logs may be relevant.

**Comment by shasheene** [comment] 2020-01-24 02:46
I think I know what went wrong for the both of you.

It looks like what happened is the 'xserver-xorg-video-all' metapackage used to install all the open-source drivers has been demoted to a [recommended package](https://launchpad.net/ubuntu/+source/xorg/1:7.7+16ubuntu1) of [xserver-xorg](https://packages.ubuntu.com/bionic/xserver-xorg) instead of a dependency.

This change was integrated Ubuntu starting from Ubuntu 17.04 (Zesty) and is why Rescuezilla v1.0.5.0 (based on Ubuntu 18.04) requires safe mode on your hardware but Redo Backup and Recovery v1.0.4 did not.

For reference, here are the xserver packages installed on Rescuezilla v1.0.5:
```
# dpkg --get-selections | grep xserver
xserver-xorg-core-hwe-18.04                     install
xserver-xorg-hwe-18.04                          install
xserver-xorg-input-all-hwe-18.04                install
xserver-xorg-input-libinput-hwe-18.04           install
xserver-xorg-video-vesa-hwe-18.04               install
```

...compared to Redo Backup and Recovery v1.0.4:
```
# dpkg --get-selections | grep xserver

x11-xserver-utils                               install
xserver-common                                  install
xserver-xorg                                    install
xserver-xorg-core                               install
xserver-xorg-input-all                          install
xserver-xorg-input-evdev                        install
xserver-xorg-input-mouse                        install
xserver-xorg-input-synaptics                    install
xserver-xorg-input-vmmouse                      install
xserver-xorg-input-wacom                        install
xserver-xorg-video-all                          install
xserver-xorg-video-ati                          install
xserver-xorg-video-cirrus                       install
xserver-xorg-video-fbdev                        install
xserver-xorg-video-geode                        install
xserver-xorg-video-intel                        install
xserver-xorg-video-mach64                       install
xserver-xorg-video-mga                          install
xserver-xorg-video-neomagic                     install
xserver-xorg-video-nouveau                      install
xserver-xorg-video-openchrome                   install
xserver-xorg-video-qxl                          install
xserver-xorg-video-r128                         install
xserver-xorg-video-radeon                       install
xserver-xorg-video-s3                           install
xserver-xorg-video-savage                       install
xserver-xorg-video-siliconmotion                install
xserver-xorg-video-sis                          install
xserver-xorg-video-sisusb                       install
xserver-xorg-video-tdfx                         install
xserver-xorg-video-trident                      install
xserver-xorg-video-vesa                         install
xserver-xorg-video-vmware                       install
```

@AlphaBootis, can you boot into regular non-safe mode, and try `sudo apt-get update && sudo apt-get install xserver-xorg-video-intel-hwe-18.04 && sudo systemctl restart slim`?

The graphical session should now start without issues. When you have a chance, please confirm this and respond.

**Comment by AlphaBootis** [comment] 2020-01-24 10:33
Yes, i can hereby confirm installing the xserver-xorg-video-intel-hwe-18.04  makes slim start normally. Nice find!

**Comment by shasheene** [comment] 2020-01-24 11:04
OK thanks for the confirmation @AlphaBootis. I will create and merge the patch for the missing packages issue later this week.

@FluorescentGreen5, your Acer Aspire One D257 also uses an Intel graphics chip (GMA 3150). Just so I can confirm the fix, can you boot into regular non-safe mode with Rescuezilla v1.0.5, then login with 'ubuntu' user and no password and run `sudo apt-get update && sudo apt-get install xserver-xorg-video-intel-hwe-18.04 && sudo systemctl restart slim`? Just like @AlphaBootis, the graphical session should then start without issues and you should be running at the native display resolution etc. When you have a chance please confirm this and respond.

Assuming it does also fix @FluorescentGreen5's issue, I will close this GitHub issue. The Ubuntu splash screen (called plymouth) being "deep fried" will remain for safe mode in the v1.0.5.1 release, but should be gone for regular mode during booting. Due to lack of persistence won't be easily able to test the normal mode booting behavior until after the ISO is released. Either way, if the issue is reproducible in a normal Ubuntu release (using the same Rescuezilla safe-mode kernel parameters), then it is best reported to the Ubuntu 'Launchpad' bug tracker.

An ISO image containing the missing packages will be rolled out as part of the v1.0.5.1 release (no estimate of when this will be done, but hopefully in the few weeks).

**Closed** 2020-01-25 08:18 UTC
Labels: bug

**Comment by shasheene** [comment] 2020-03-24 05:52
@FluorescentGreen5, @Kevinsky86 

[Rescuezilla v1.0.5.1](https://github.com/rescuezilla/rescuezilla/releases/tag/1.0.5.1) has now been released and has many improvements, including fixing this bug.

Please let me know if you have any issues with Rescuezilla v1.0.5.1.

**Comment by FluorescentGreen5** [comment] 2020-04-05 08:26
It now works without having to use safe mode, only complaining about an undefined video mode on the netbook (it eventually figures itself out after hitting space). Thanks!

**Comment by Kevinsky86** [comment] 2020-04-08 16:49
This also seems fixed here.
