### ISSUE TITLE
Cannot connect to smb folder

### ISSUE THREAD

**Issue by fokerone** [rescuezilla/rescuezilla#22] opened 2019-11-14 17:23 UTC
When i  try to restore a backup from a remote folder and try to connect to  a smb folder using the IP instead of DNS name, redo says that cannot connect to the resource. This featured is working in the .4 version.

**Comment by shasheene** [comment] 2019-11-15 02:12
Hi fokerone,

There has been some minor changes to the SMB (and FTP) client behavior since v1.0.4. This was mainly to support special characters in passwords, and to avoid writing passwords to log file.

Rescuezilla v1.0.5 was tested against a Windows 10 machine configured to share a directory using the built-in SMB/CIFS server. During testing, an IP address was used, and a username and password (including special characters) and an empty domain field. I did not test DNS name (sounds like it worked for you), nor modifying the domain field. I have successfully retested SMB using an IP address using v1.0.5.

Can you provide more information SMB settings you are using?

**Comment by fokerone** [comment] 2019-11-15 12:08
Hi shasheene!,
Thank for you response!, the folder that i try to connect it's a Ubuntu with  SMB shared folders.
I can start the RescueZilla wizard from the console, to look what is happen backwards, and trow more information to you?

Regards!

**Comment by fokerone** [comment] 2019-11-19 13:51
Hi shasheene, I execute in terminal 'rescuezilla-pkexec' and try again to conect, and capture the error:

*Executing: mount.cifs '//192.168.xxx.xxx' /mnt/backup -o credentials='/tmp/tmp.pjfBBTzYHn' 
mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page ( e.g man mount cifs)

I hope this help to resolve the problem!
regars

**Comment by fokerone** [comment] 2019-11-19 14:37
Ok i found the solution descripted here : [https://askubuntu.com/questions/967229/mount-cifs-for-mounting-nas-unit-not-working-on-17-10](url)

adding vers=1.0 to the options it's work, so the problem is mount.cifs with old smb servers 
:)

**Comment by shasheene** [comment] 2019-11-21 02:34
I will look into adding a radio button to select the SMB/CIFS protocol version

**Comment by shasheene** [comment] 2019-11-21 02:37
Nice work debugging! I remember now having to add the version to the mount.cifs call to get it to work with Windows 10, but I didn't make that change clear in the CHANGELOG, sorry.

The best solution appears to be to add a radio button to select the SMB/CIFS protocol version.

**Comment by AlphaBootis** [comment] 2019-11-21 13:53
I want to confirm running into same issue with linux based share, workound as described by @fokerone also worked here.
File server I get this from has SMB2 protocol enabled though, not sure what's going on here right out of the gate. Will do some further testing when I find the time.

**Comment by shasheene** [comment] 2020-01-30 09:25
OK. I was able to reproduce the issue on Ubuntu 12.04. Both Windows 10 and Lubuntu 19.10 do not need the field populated. I have implemented a fix for this:

![SMB](https://user-images.githubusercontent.com/1414379/73435861-5b5b7880-4399-11ea-9a28-254cfb2e4734.png)
![FTP](https://user-images.githubusercontent.com/1414379/73435862-5bf40f00-4399-11ea-9b21-6814b2c78e30.png)

Instead of a radio button, I ended up deciding on a simple text-field. Just like the 'domain' field, it is only editable for the SMB, but not the FTP. It's not ideal, so [#6](https://github.com/rescuezilla/rescuezilla/issues/6#issuecomment-580057438) continues to capture detail about usability improvements.

I did notice a bug where in v1.0.5 the 'domain' field was no longer being correctly passed to the mount.cifs command. This has been fixed.

I also noticed that in v1.0.5, the FTP connections seem very unstable (connects and starts backing up correctly, but the connection drops out) when connecting to vsftp on Lubuntu 19.04. This is strange and requires more investigation because v1.0.5 FTP connections were successfully tested before.

**Closed** 2020-01-30 09:45 UTC
Labels: bug

**Comment by shasheene** [comment] 2020-01-30 09:46
So this fix will be in v1.0.5.1 which will hopefully be released at some point in the next several weeks.

**Comment by shasheene** [comment] 2020-03-24 05:53
@fokerone, @Kevinsky86 

[Rescuezilla v1.0.5.1](https://github.com/rescuezilla/rescuezilla/releases/tag/1.0.5.1) has now been released.

Please let me know if you have any issues with Rescuezilla v1.0.5.1.

**Comment by Kevinsky86** [comment] 2020-04-01 17:11
Hi @shasheene , I will test this soon. I've been a bit low on time due to this pandemic and lacked any pc's that needed imaging as of late.

**Comment by Kevinsky86** [comment] 2020-04-08 16:44
@shasheene This solution works like a charm.

**Comment by fokerone** [comment] 2020-04-08 17:16
@shasheene  like @Kevinsky86 said! it's  works great!!!!

**Comment by shasheene** [comment] 2020-06-18 03:25
@fokerone, @Kevinsky86 

Sorry to bother you both. [Rescuezilla v1.0.6](https://github.com/rescuezilla/rescuezilla/releases/latest) has now been released, and has some features you may be interested in: support for special characters in the UNC path (including backslashes), display of the mount.cifs output on error and actual support of EFI Secure Boot support.

It definitely worth upgrading, but you may prefer to stick to the 32-bit version for now (continuing to be based on Ubuntu 18.04 like prior versions) as there's some slowdown in the shutdown on the 64-bit version that I'm investigating. If you do upgrade, please read the bug advisories section as there a low severity issue around samba servers hosted on Ubuntu 20.04 systems that you guys may have some ideas on.

If you have any issues with Rescuezilla v1.0.6, please let me know.

Also, you may want to know that the original developer of _Redo Backup and Recovery_ has recently [resurfaced after a 7.5 year absence to release an incompatible update named _Redo Rescue_ v2.0.0](https://sourceforge.net/p/redobackup/discussion/1169663/thread/d0e37c4750/). You may be interested in evaluating it. It has many features I am intending on adding for Rescuezilla v1.0.7.

**Comment by Kevinsky86** [comment] 2020-06-18 09:47
I will check this out, thank you.
Currently have no imaging work planned but i'll drop feedback as soon as i
tried it.

Op do 18 jun. 2020 om 05:25 schreef Shasheen Ediriweera <
notifications@github.com>:

**Comment by fokerone** [comment] 2020-06-18 13:12
Hi! i will check this version and let you know !
