### ISSUE TITLE
How to fix mismatched GPT and MBR partition

### ISSUE THREAD

**Issue by candrapersada** [rescuezilla/rescuezilla#94] opened 2020-06-19 04:50 UTC
it will affect clonezilla

```
MBR: MBR only
BSD: not present
APM: not present
GPT: Damaged
```

**Comment by shasheene** [comment] 2020-06-19 06:05
Hi candrapersada,

I have just created a discussion forum for [Rescuezilla support queries](https://sourceforge.net/p/rescuezilla/discussion/support/). Please keep all Rescuezilla support queries on that forum so that the GitHub Issues can be maintained only for development tasks.

I was unable to reproduce your issue using Rescuezilla v1.0.6. I tested a GPT disk and tried a whole disk backup and restore (the only officially supported approach), then used Clonezilla to do a backup and restore. I had no issues. For internal testing, I erased the disk completely before each restore.

I tried the _unofficial_ and _unsupported_ method of using Rescuezilla v1.0.6) to make multiple backups partitions individually (remember Rescuezilla v1.0.6 only officially supports backup and restore of entire disks) I modified files on each of the partitions slightly, then used Rescuezilla to restore one of the partitions. Both the MBR and GPT partition tables were still fully consistent and I was able to make a backup/restore using Clonezilla.

Given the GitHub issue you created on the Redo Rescue GitHub issue (https://github.com/redorescue/redorescue/issues/9) it sounds like you may have used Redo Rescue to create an inconsistent state in your disk. There is the protective MBR, the Primary GPT and the Secondary GPT. You may have done something to cause an inconsistent state between them. I speculate you may be able to fix this by making a modification to the partitions using GParted to have that application write a new MBR and both GPTs consistently, but I have not tested this.

I re-iterate that, at this stage, I am not providing user support for Redo Rescue v2.0.0 or Clonezilla. I am happy to provide support for restoring backups created with Rescuezilla using Rescuezilla, but it appear that  is not the problem here.

I have just created a discussion forum for [Rescuezilla support queries](https://sourceforge.net/p/rescuezilla/discussion/support/). Please any Rescuezilla support queries on that forum so that the Rescuezilla GitHub Issues can be maintained for development tasks only.

**Comment by shasheene** [comment] 2020-06-19 07:24
I am closing this issue as invalid as there is enough evidence to suggest this is not an issue caused by Rescuezilla, but rather the use of the Redo Rescue v2.0.0 project to move around partitions (a project developed independently of Rescuezilla).

I will re-open this issue (or at least create a more clearly defined issue linking to this one) in the unlikely event that the issue you're experiencing was caused by Rescuezilla.

**Closed by shasheene** 2020-06-19 07:24 UTC
Labels: invalid

**Comment by shasheene** [comment] 2020-06-19 13:39
@candrapersada 

I have looked at all the issues you have created between Rescuezilla and Redo Rescue in the past day or so.

Can you tell me if Rescuezilla was involved in what you have done to your disks? It sounds like you have tried to backup your "KDE Neon partition mbr" using with Redo Rescue, and Rescuezilla was not involved at all.

Is this correct?

Can you please explain everything you have done until now step by step?

**Comment by redorescue** [comment] 2020-06-19 23:36
Just for clarity, the user mentioned using Redo's selective restore mode. When using Redo's partitioning remapping feature (selective restore mode), absolutely NO information is written to the master boot record or partition tables. They are not modified at all. Data is only written to the selected partition(s). It goes without saying that reordering partitions (while leaving the partition table untouched) will certainly break its ability to boot afterward.

**Comment by shasheene** [comment] 2020-06-20 08:21
Thanks @zebradots for confirming Redo does not modify either the legacy DOS (MBR) partition table, or the modern GPT partition table during the use of Redo's selective restore mode (I wasn't sure).

I note that from candrapersada's GitHub posts, it sounds like this user has been using Redo Rescue, Rescuezilla _and_ Clonezilla, and we do not yet know exactly what operations they have done.

I agree it's likely that candrapersada has broken the _boot_ of their machine using Redo Rescue v2.0.0 through reordering partitions. However, I was worried that there's way to use Rescuezilla that can cause the primary and secondary GPT to reach an inconsistent state.

I tested out some theories around Rescuezilla experimental "smaller than original" support. I **was able** to reproduce an inconsistent GPT state through the experimental support for restoring to a disk smaller than the original. I have described this problem in the Rescuezilla GitHub issue #96.

@candrapersada can you confirm whether or not you experienced Rescuezilla issue #96? In other words, did you try to restore your Rescuezilla backup to a disk that was smaller than the original? If so, please try restoring your Rescuezilla backup to a drive of equal or larger capacity than your original backup.

**Comment by zebradots** [comment] 2020-06-24 02:18
Hi @shasheene! I see this is closed but wanted to update you and anyone else wondering about this issue: This is _not_ a bug in Rescuezilla (or Redo). We were able to determine that @candrapersada had used another utility that altered the partition table (https://github.com/redorescue/redorescue/issues/10#issuecomment-647074206).

**Comment by shasheene** [comment] 2020-06-24 02:54
@zebradots That's great to hear! Thanks for the confirmation/clarification
