### ISSUE TITLE
IDE Restore requires SATA controller

### ISSUE THREAD

**Issue by Phil795** [rescuezilla/rescuezilla#26] opened 2019-11-29 09:38 UTC
I am currently working with Redo Backup 1.0.4
If I want to backup a machine with a SATA controller safely, but want to restore it via an IDE controller, it is necessary that the PC (with me a VM in Vbox) has a SATA controller with a hard disk. Without this useless SATA controller with HDD, the restore process ends after one second.

**Comment by shasheene** [comment] 2019-11-29 12:13
Hi Phil795,

I don't fully understand the question. All connected hard drives need to talk to a controller. If you're using VirtualBox with two virtual harddrives (VDI files), you can attach/remove VDI files between the IDE and SATA controllers without using Redo Backup.

If you're using VirtualBox just as test environment, then in theory you should be able to backup a SATA harddrive and restore it to an IDE harddrive (and vice versa), if the destination drive is larger than the source drive. However I haven't tested this. The underlying hard drive shouldn't matter much as Linux presents applications like Redo Backup with device nodes. For SATA devices these are /dev/sda1, /dev/sda2, /dev/sdb etc. For IDE devices these nodes are /dev/hda1, /dev/hda2 etc. For NVMe drives these are /dev/nvme0n1 etc. Redo Backup v1.0.5 has been tested against SATA drives and NVMe drives to check if bugs have been introduced since v1.0.4.

Please clarify your problem.

**Comment by shasheene** [comment] 2020-02-09 02:51
While your problem is best solved by using a SATA controller in VirtualBox, you are indeed correct that IDE drives are not supported on Rescuezilla v1.0.5 and earlier Redo Backup and Recovery releases.  Additionally, I incorrectly stated NVMe drives are supported in Rescuezilla v1.0.5. My apologies.

Support for IDE drives (/dev/hda1, /dev/hda2 etc) device nodes will be added in the next release, as the changes I have implemented for NVMe drives (#27) will handle both. This should be fixed and rolled out in v1.0.5.1 in the next few weeks.

**Comment by shasheene** [comment] 2020-02-25 11:38
Hi @Phil795,

While your problem is best solved by using a SATA controller in VirtualBox, I now understand the issue you are reporting and have reproduced it.

What you are saying that a backup of an IDE/PATA drive on Redo Backup and Recovery v1.0.4 does not restore on Rescuezilla v1.0.5. The issue here was the IDE/PATA device node on the Linux kernel used in Rescuezilla v1.0.5 wasn't necessarily the same device node on Redo Backup and Recovery v1.0.4, which caused you to hit a bug that I've happened to have hit elsewhere recently:

> In short, the root cause is the destination partition having the same device name as the original source partition, which causes the hard drive containing backup to be unmounted as the restore progress. This bug has been with Redo Backup and Recovery since the first release in June 2010, which is crazy!

The complete details are in #36. The fix I have created for this will be part of v1.0.5.1 which will be released soon.

Also for completeness, I will mention some of my mistakes/misconceptions. I incorrectly stated NVMe drives are supported in Rescuezilla v1.0.5. That was wrong, NVMe support is coming in v1.0.5.1. I also incorrectly stated in another comment (which I have now deleted) that IDE/PATA drives are not supported by Rescuezilla. Both Rescuezilla v1.0.5, v1.0.4 (and likely earlier releases) support IDE/PATA without issues and I have confirmed this in a VM. I was under mistaken impression they were populated under the device nodes in the form /dev/hda1, /dev/hdb1 device nodes, and used my knowledge of the inner workings of the script itself I know those devices would not work. Here my knowledge of where an IDE/PATA drive on Linux is populated is well out-of-date. For at least a decade, IDE/PATA drives are populated under /dev/sda1, /dev/sda2 (just like SATA drives).

As mentioned, the issue you identified is fixed and will be released as part of v1.0.5.1 soon. I am closing this issue and labeling it as a duplicate.

**Closed by shasheene** 2020-02-25 11:38 UTC
Labels: bug

**Comment by shasheene** [comment] 2020-03-24 05:51
Hi @Phil795,

[Rescuezilla v1.0.5.1](https://github.com/rescuezilla/rescuezilla/releases/tag/1.0.5.1) has now been released. As mentioned, the bug you identified has been fixed. Thank you for your report.

Please let me know if you have any issues with Rescuezilla v1.0.5.1.
