### ISSUE TITLE
Backup of BTRFS filesystem fails with "couldn't open because of unsupported features error (10)"

### ISSUE THREAD

**Issue by joshontech** [rescuezilla/rescuezilla#168] opened 2021-01-17 06:42 UTC
I keep getting this error

![IMG_20210117_013617.jpg](https://user-images.githubusercontent.com/44295541/104833233-2758bc00-5865-11eb-84d9-07dd28b6ab44.jpg)

**Comment by shasheene** [comment] 2021-01-17 08:03
Hi Josh,

**There is an open issue in the partclone project about this: https://github.com/Thomas-Tsai/partclone/issues/149**

**The error indicates the `partclone.btrfs` application used internally was unable to process your BTRFS filesystem. The `partclone.btrfs` application is used to make a "filesystem aware" backup that reads the filesystem structures to only copy used blocks.**

I should note I have often considered modifying Rescuezilla's internal logic to ask the user if they would like to make a "sector-by-sector" image if their "filesystem-aware" backup has failed, but I haven't figured out how to implement user-experience that I'm happy with.

I should also note the most recent Rescuezilla release (v2.1.2) is based on Ubuntu 20.10 "Groovy" which uses [partclone v0.3.13](https://packages.ubuntu.com/groovy/partclone). This version is getting relatively old so for future Rescuezilla versions I am intending on building partclone from source to provide Rescuezilla users with a more recent version. Of course this won't fix your issue yet given that as of writing https://github.com/Thomas-Tsai/partclone/issues/149 hasn't actually fixed the problem.

**Comment by joshontech** [comment] 2021-01-17 08:09
Thanks for the response! Well looks like btrfs is the issue.

**Comment by shasheene** [comment] 2021-01-17 08:20
Yep! I will make sure Rescuezilla has the most recent version of partclone for subsequent versions because that will definitely help things.

The next version of Rescuezilla is currently scheduled for after April 2021 which is still a few months away. That release will definitely improve things for you.

Until then it's possible to make "sector-by-sector" images using Clonezilla's Expert Mode by selecting the "dd" (or "partclone.dd") imaging mode. But Clonezilla is difficult to use and 'dd' produces a very large backup image which might not be feasible if you're making a backup of a very large partition.

**Comment by joshontech** [comment] 2021-01-17 08:24
Thanks! It looks like as I was reading about the new version of partclone has the fix for this so yea using the git version will fix this.

I will just have to use the built in btrfs send/receive feature to do my backups it seems really robust. I have been using btrfs for years and never even looked into it 😅

**Comment by MarcelKuesters** [comment] 2022-01-18 23:36
Hi Sha...

i have still this problem with my actual backup of my Archlinux BTRFS Timeshift @ and @home  layout with zstd compress option.
with the latest Rescuezilla

https://i.imgur.com/wThORcv.png

Are these Clonezilla's Expert Modes integrated in latest Rescuezilla ?
Did you integrate the latest partclone?

Thanks for help and answers.

Marcel

**Comment by MarcelKuesters** [comment] 2022-01-22 15:10
Hi,

i did setup a new system with Snapper and compress off in fstab, so backup is working fine, just for your info.

Thanks.
Marcel

**Comment by MarcelKuesters** [comment] 2022-01-22 15:11
> Hi Sha...
> 
> i have still this problem with my actual backup of my Archlinux BTRFS Timeshift @ and @home layout with zstd compress option. with the latest Rescuezilla
> 
> https://i.imgur.com/wThORcv.png
> 
> Are these Clonezilla's Expert Modes integrated in latest Rescuezilla ? Did you integrate the latest partclone?
> 
> Thanks for help and answers.
> 
> Marcel

**Comment by MarcelKuesters** [comment] 2022-01-22 15:11
> Hi Sha...
> 
> i have still this problem with my actual backup of my Archlinux BTRFS Timeshift @ and @home layout with zstd compress option. with the latest Rescuezilla
> 
> https://i.imgur.com/wThORcv.png
> 
> Are these Clonezilla's Expert Modes integrated in latest Rescuezilla ? Did you integrate the latest partclone?
> 
> Thanks for help and answers.
> 
> Marcel

Hi,

i did setup a new system with Snapper and compress off in fstab, so backup is working fine, just for your info.

Thanks.
Marcel

**Comment by shasheene** [comment] 2022-01-22 15:21
Whoops forgot to reply.

No, I haven't started compiling the most recent version of partclone from source code. I hope to do so for the upcoming version of Rescuezilla to be released in a few weeks.

**Comment by ZaxLofful** [comment] 2022-01-27 23:31
I am one of those weird people, that actually have a use case for this. I have a BRTFS file system that does the ZSTD transparent compression (Synology and Proxmox). So I could really use this feature, for now I have found other ways around it (had to destroy some data [sadface]); but I really could have used the feature about 2 weeks ago.

**Comment by MarcelKuesters** [comment] 2022-01-28 12:50
> I am one of those weird people, that actually have a use case for this. I have a BRTFS file system that does the ZSTD transparent compression (Synology and Proxmox). So I could really use this feature, for now I have found other ways around it (had to destroy some data [sadface]); but I really could have used the feature about 2 weeks ago.

Hi,
after testing a while with my system (Archlinux with XFCE4 BTRFS and Snapper Grub Boot for restoring) i found out that the problem ist not at partclone. The problem itself is on BTRFS Filesystem. After removing Snapper and Snapper Grub from my system, because restoring did not work, i did notice that compress off or on in fstab did not help me to backup my ssd with rescuezilla. I get always an error from partclone.

What did happen?

In Rescuezilla i did mount my BRTFS Filsystem and did remove the subvolume from Snapper i only leave @, @home and
@var_log
But this actions seems to be corrupt my BTFRS filesystem and partclone seems to reconize this and endet with errors.

Now what?

I did repair my BTRFS filesystem with the comands given  below:

https://btrfs.readthedocs.io/en/latest/btrfs-check.html

!!!Attention!!
Backup up your ssd with your corrupt filystem befor you do any command to repair it. Use no compression in Rescuezilla.

So first i did a  "--repair" ond my ssd.
That showed me allot of errors and a checksum error.

So second i did a "--init-csum-tree" on my ssd.
That did take 15 minutes for my 120 GB ssd.

After that i did a second "--repair", checksum error gone.

Then i did a balance on my BTRFS.

After a reboot i startet up Rescuezilla again and i could do a normal backup with gzip compression.
Fine :-)

No i did backup my BTRFS with Timeshift and rsync to my external harddrive with @, @home and @var_log folders.
Restoring is doing very well and i can test a lot of my new Archlinux on my old iMac 2013. Like Mac OSX and Timemachine.

:-)

**Comment by joshontech** [comment] 2022-02-26 19:04
> > I am one of those weird people, that actually have a use case for this. I have a BRTFS file system that does the ZSTD transparent compression (Synology and Proxmox). So I could really use this feature, for now I have found other ways around it (had to destroy some data [sadface]); but I really could have used the feature about 2 weeks ago.
> 
> Hi, after testing a while with my system (Archlinux with XFCE4 BTRFS and Snapper Grub Boot for restoring) i found out that the problem ist not at partclone. The problem itself is on BTRFS Filesystem. After removing Snapper and Snapper Grub from my system, because restoring did not work, i did notice that compress off or on in fstab did not help me to backup my ssd with rescuezilla. I get always an error from partclone.
> 
> What did happen?
> 
> In Rescuezilla i did mount my BRTFS Filsystem and did remove the subvolume from Snapper i only leave @, @home and @var_log But this actions seems to be corrupt my BTFRS filesystem and partclone seems to reconize this and endet with errors.
> 
> Now what?
> 
> I did repair my BTRFS filesystem with the comands given below:
> 
> https://btrfs.readthedocs.io/en/latest/btrfs-check.html
> 
> !!!Attention!! Backup up your ssd with your corrupt filystem befor you do any command to repair it. Use no compression in Rescuezilla.
> 
> So first i did a "--repair" ond my ssd. That showed me allot of errors and a checksum error.
> 
> So second i did a "--init-csum-tree" on my ssd. That did take 15 minutes for my 120 GB ssd.
> 
> After that i did a second "--repair", checksum error gone.
> 
> Then i did a balance on my BTRFS.
> 
> After a reboot i startet up Rescuezilla again and i could do a normal backup with gzip compression. Fine :-)
> 
> Now i did backup my BTRFS with Timeshift and rsync to my external harddrive with @, @home and @var_log folders. Restoring is doing very well and i can test a lot of my new Archlinux on my old iMac 2013. Like Mac OSX and Timemachine.
> 
> :-)

This is extremely interesting because I have heard that using the --repair command with btrfs is not recommended. It is almost always better to use a scrub than a --repair so I wonder what --repair did to clear the rescuzilla/partclone issue? 

Have you tried restoring that image you created with rescuzilla?

**Comment by MarcelKuesters** [comment] 2022-02-27 08:55
> > > I am one of those weird people, that actually have a use case for this. I have a BRTFS file system that does the ZSTD transparent compression (Synology and Proxmox). So I could really use this feature, for now I have found other ways around it (had to destroy some data [sadface]); but I really could have used the feature about 2 weeks ago.
> > 
> > 
> > Hi, after testing a while with my system (Archlinux with XFCE4 BTRFS and Snapper Grub Boot for restoring) i found out that the problem ist not at partclone. The problem itself is on BTRFS Filesystem. After removing Snapper and Snapper Grub from my system, because restoring did not work, i did notice that compress off or on in fstab did not help me to backup my ssd with rescuezilla. I get always an error from partclone.
> > What did happen?
> > In Rescuezilla i did mount my BRTFS Filsystem and did remove the subvolume from Snapper i only leave @, @home and @var_log But this actions seems to be corrupt my BTFRS filesystem and partclone seems to reconize this and endet with errors.
> > Now what?
> > I did repair my BTRFS filesystem with the comands given below:
> > https://btrfs.readthedocs.io/en/latest/btrfs-check.html
> > !!!Attention!! Backup up your ssd with your corrupt filystem befor you do any command to repair it. Use no compression in Rescuezilla.
> > So first i did a "--repair" ond my ssd. That showed me allot of errors and a checksum error.
> > So second i did a "--init-csum-tree" on my ssd. That did take 15 minutes for my 120 GB ssd.
> > After that i did a second "--repair", checksum error gone.
> > Then i did a balance on my BTRFS.
> > After a reboot i startet up Rescuezilla again and i could do a normal backup with gzip compression. Fine :-)
> > Now i did backup my BTRFS with Timeshift and rsync to my external harddrive with @, @home and @var_log folders. Restoring is doing very well and i can test a lot of my new Archlinux on my old iMac 2013. Like Mac OSX and Timemachine.
> > :-)
> 
> This is extremely interesting because I have heard that using the --repair command with btrfs is not recommended. It is almost always better to use a scrub than a --repair so I wonder what --repair did to clear the rescuzilla/partclone issue?
> 
> Have you tried restoring that image you created with rescuzilla?

Yes, often times. After every Kernel Update on my iMac. Actual Kernel is 5.16.10-arch1-1. The latest restore was on my old Mac Mini from 2011 in my living room. But the latest Version was 5.16.8 that I could install on my Mac Mini, after that I got a kernel panic. So from every Master Backup that I have from my iMac, I also did make a verifying of the image in Rescuezilla. So if my iMac gets broken, I can restore my system on any new modern Pc or iMac. :-) In every room where I have a PC or iMac, I have the same system running.

The actual scrub of my SSD.
https://imgur.com/Mm5dNmE.png

The Normal way should be, first to do a scrub.

But as a Note on the BTRFS website says:

"Note

Scrub is not a file system checker (fsck) and does not verify nor repair structural damage in the file system. It really only checks checksums of data and tree blocks, it doesn’t ensure the content of tree blocks is valid and consistent. There’s some validation performed when metadata blocks are read from disk, but it’s not extensive and cannot substitute full btrfs check run.”

But in my case, after I did a scrub, I get errors on my SSD as described above, so I did a repair.

**Comment by shasheene** [comment] 2022-07-24 20:20
Update: the latest version of `partclone` is now being built from source. It's available in Rescuezilla "Weekly" Rolling Release (2022-07-24) which will form the basis of Rescuezilla v2.4.

**Comment by joshontech** [comment] 2023-02-04 01:59
> Update: the latest version of `partclone` is now being built from source. It's available in Rescuezilla "Weekly" Rolling Release (2022-07-24) which will form the basis of Rescuezilla v2.4.
> 

Thanks for keeping us posted! I actually have not tested this yet due to the fact that I have been encrypting everything and Rescuzilla has been working with that flawlessly. I definitely need to test this asap though because btrfs support would be a huge improvement!

**Closed** 2023-11-26 22:25 UTC
