### ISSUE TITLE
Rescuezilla loses drive in list 

### ISSUE THREAD

**Issue by Abejjr** [rescuezilla/rescuezilla#181] opened 2021-01-30 15:39 UTC
Apologies, this is my first bug post.

Rescuezilla lists /dev/sda (the storage partition) when I am selecting the partition(s) to back up from (/dev/nvme0n1), but after /dev/nvme0n1 partitions are selected to save, then /dev/sda disappears from the drive list.  At all times /dev/sda is visible from fdisk or parted.  When Rescuezilla is used to restore /dev/sda is missing from the list at the beginning.

> root@ubuntu:~/b/0rin/Bins# parted -l
Model: ATA Samsung SSD 860 (scsi)
Disk /dev/sda: 500GB
Sector size (logical/physical): 512B/512B
Partition Table: loop
Disk Flags: 

Number  Start  End    Size   File system  Flags
 1      0.00B  500GB  500GB  ext4

**Comment by Abejjr** [comment] 2021-01-30 15:53
[parted -l.txt](https://github.com/rescuezilla/rescuezilla/files/5898222/parted.-l.txt)
[fdisk -l.txt](https://github.com/rescuezilla/rescuezilla/files/5898223/fdisk.-l.txt)

Will add screenshot next.

**Comment by Abejjr** [comment] 2021-01-30 16:09
Couldn't take a screenshot with the drive list dropdown exposed.

**Comment by shasheene** [comment] 2021-01-31 01:27
From what I can tell, the root cause of this is your 500GB Samsung SSD does not have a partition table: the filesystem has been written directly on a disk. Your other disks do correctly have a partition table, that's why you can see "/dev/sdbN" and "/dev/nvme0n1pN" -- the letter N shows the partition number, but not "/dev/sda1"

I intend on [improving the situation with filesystems directly on the disk](https://github.com/rescuezilla/rescuezilla/issues/43#issuecomment-708103789), but there's not actually any benefit of formatting your 500GB Samsung SSD _without_ a partition table.

**So as an easy workaround**, I recommend you make a copy of any important files from the storage drive and very carefully **use GParted to create a GPT partition table**, and then create a fresh ext4 filesystem. This will delete any files on this drive. Once this has been completed, you should be able to "see" the /dev/sda1 partition from Rescuezilla.

Let me know if you have any issues/questions! Also, please be very careful when using GParted.

**Comment by shasheene** [comment] 2021-02-02 02:55
@Abejjr [has said](https://github.com/rescuezilla/rescuezilla/issues/180#issuecomment-771305848) the workaround above worked, so I'm closing this issue:

> Thank you Shasheen.  It worked like magic!

**Closed by shasheene** 2021-02-02 02:55 UTC

**Comment by shasheene** [comment] 2021-02-02 02:57
I hope you and anybody else reading this comment considers [giving a "like" on AlternativeTo](https://alternativeto.net/software/rescuezilla/about/) so that more people can discover Rescuezilla. Currently the project only has 18 likes compared to Clonezilla's 414 likes, which is causing fewer people to discover the application.
