### ISSUE TITLE
Rescuezilla as a Standalone Ubuntu Package

### ISSUE THREAD

**Issue by FluorescentGreen5** [rescuezilla/rescuezilla#119] opened 2020-09-18 17:05 UTC
Would it be possible for the Rescuezilla application to be available as a package that can be installed via `apt`?

**Comment by shasheene** [comment] 2020-09-19 01:41
Thanks for raising this.

Yes, Rescuezilla has always been intended to become available through `apt-get`. This will allow any Linux environment based on the Debian package repositories (such as Ubuntu and Linux Mint) to install the Rescuezilla frontend application with minimal effort.

I'm sorry I haven't done this yet. I have been focusing my limited time on the major Rescuezilla upgrade that is scheduled for release in mid-October 2020 (a few weeks from now). Among other enhancements, this new release finally adds the ability to backup and restore hard drives in Clonezilla image format, and the ability to restore partitions individually.

I will be starting the process of ascension to the Debian repositories after I have released this next version. Debian packaging is well-known to be an extremely painful process. The Debian maintainers can (and should) tear the Rescuezilla to shreds. But the grueling process will provide increased rigor to Rescuezilla. Certainly it will force me to research and implement Debian's "Reproducible Build" best practices (as part of task #104).

Side note: I consider reproducible builds and ascension to the Debian repositories an absolute must before users start widely making backups of decrypted LUKS drives as part of task #42. Rescuezilla ISO images are far more difficult to audit compared compared to a simple reproducible deb package in the official Debian repositories.

As you may know, Rescuezilla is already packaged as a `deb` file internally. While the build instructions already provide a mechanism to construct and install a deb file, this is very difficult for most users, not least because it's most easily built using very complex applications like `docker`. Until Rescuezilla has been included in the Debian repositories, it makes sense to release this deb file along with the 32-bit and 64-bit Rescuezilla ISO images. Indeed, this deb file will continue to be important because it takes many months or years for updated Debian packages to make their way into Debian Stable and the current Ubuntu release, and there will almost always be a more recent Rescuezilla release by that time.

From my past experience, there is a significant amount of work handling changes in utilities used internally like `partclone` and `sfdisk`. I expect making Rescuezilla widely available through the Debian repositories will add significant amount of support overhead: until now Rescuezilla has been operating in a known package environment, which makes debugging _much_ easier. 

But it's the correct thing to do.

**Comment by shasheene** [comment] 2020-12-12 10:15
To anybody reading this, [Rescuezilla v2.1](https://github.com/rescuezilla/rescuezilla/releases/latest) makes a standalone Rescuezilla deb package available as a release artifact.

The deb package can be downloaded at the bottom of the releases page (under the Assets section).

It merely includes the Rescuezilla Python scripts, image assets, and a basic requirements.txt file. I haven't written simple instructions, and it's been a while since I have confirmed the current requirements.txt is sufficient.

Hopefully advanced users are able to work out how to install the package and configure the virtualenv has required. As mentioned in [#120](https://github.com/rescuezilla/rescuezilla/issues/120#issuecomment-742278476), I still haven't found a satisfactory way to achieve this that meets my design goals (input welcome).

Also `[partclone-nbd](https://github.com/rescuezilla/partclone-nbd)` is a dependency of Rescuezilla v2.1's Image Explorer functionality. It's not available from package managers so you'll need to compile it. Oh I forgot to list `nbdkit` as a dependency (it *is* available from a package manager).

**Comment by candrapersada** [comment] 2020-12-12 10:20
whether in future will arch linux?

**Comment by shasheene** [comment] 2020-12-12 10:34
Yes for sure. I'm sure there's somebody using Arch Linux who would be interested in taking the Rescuezilla v2.1 source code and producing a package for Arch Linux

**Comment by candrapersada** [comment] 2020-12-12 10:46
> Also `[partclone-nbd](https://github.com/rescuezilla/partclone-nbd)` is a dependency of Rescuezilla v2.1's Image Explorer functionality

can use rescuezilla without partclone-nbd dependency?

**Comment by shasheene** [comment] 2020-12-12 10:55
Yes, but then the Image Explorer functionality wouldn't work. I'm sure whoever packages Rescuezilla for Arch Linux would also go to the effort to packaging the partclone-nbd dependency. It's very simple but nobody has done it get because nobody uses `partclone-nbd` (until now)

**Comment by shasheene** [comment] 2021-05-29 13:12
I'm closing this issue because it's actually been already completed: even the v2.1.3 Rescuezilla  deb package can be installed on any Ubuntu 20.04 system. It uses the system Python install (not virtualenv), but the basic backup and restore functions works already. As per the recent discussion on #217:

> > The deb package file doesn't get tested much outside of the Rescuezilla live environment, so for Rescuezilla v2.1.3 deb package there's a few additional things that you'll need to do an unmodified (non-Rescuezilla) Ubuntu 20.04:
> 
> Try `sudo modprobe nbd` (to fix the unmount issue) and `sudo apt-get install smartmontools` (to fix another issue that would happen during a backup operation).
> 
> Then try rerunning the application. It should now work fine!
> 
> By the way, Rescuezilla v2.2 will be released at the end of this month and has a lot of new features and improvements. I will try and remember to double-check the deb package can be installed and used on an unmodified Ubuntu system with no additional effort.

Rescuezilla v2.2 deb package will of course have a smoother install than the v2.1.3 described above. 

Make sure Rescuezilla and dependencies like partclone-nbd (and in future, partclone-utils) are available in the official Debian and Ubuntu package repositories should be handled as a different task.

**Closed by shasheene** 2021-05-29 13:12 UTC
Labels: enhancement
