### ISSUE TITLE
Issue restoring Linux on iMac on Rescuezilla but not Redo

### ISSUE THREAD

**Issue by AE720** [rescuezilla/rescuezilla#132] opened 2020-10-30 03:24 UTC
This problem maybe already referenced at https://github.com/rescuezilla/rescuezilla/issues/131 but I don't know for certain. When imagining a build of Lubuntu on an iMac the follow happens with the following scenerios:

Backing up using Redo Backup and Restore works completely.

Backing up with a version of Rescuezilla before 2.0 yields the following error:

"Backup operation failed:

Failed to run comand: sgdisk --backup /mnt/backup./[IMAGE]/sda-gpt.gdisk /dev/sda

Invalid partition data!

Failed to run command: sgdisk -backup /mnt/backup/[IMAGE]/sda-gpt.gdisk /dev/sda

Invalid partition data!
"

I backup with Rescuezilla 2.0 and it seems to work but when I restore it (Also says operation was successful), there is nothing to boot to. It is worth noting that I can restore from that Redo Backup and Restore Image across all three. I'm GUESSING it's something to do with reading GPT vs MBR.

This might also propose a solution of adding a section for "Legacy backup" so I don't have to have multiple bootable media for the same task.

**Comment by shasheene** [comment] 2020-10-30 04:09
Hi @AE720,

Please upload the file named 'clonezilla-img' and the file ending in "-pt.sf" and I will analyse what went wrong. Also upload the Rescuezilla log files from your failed pre-Rescuezilla v2.0 backup.

It looks like the pre-2.0 versions of Rescuezilla appear to think your disk is GPT formatted. What does GParted say when you open it? There may be an issue with the partition table headers that needs repair.

If your disk uses legacy MBR (DOS) partitioning, almost certainly Rescuezilla 2.0 did not fully backup your Linux GRUB bootloader, due to incomplete post-MBR gap bug described by issue #103: the post-MBR gap is only needed on _some_ Linux environments that use the legacy MBR partition layout (but not all). I fixed that problem for Rescuezilla v1.0.6 (#64, #57), but at the time it was very difficult to reproduce the bug. The Rescuezilla v2.0 rewrote the entire application and **it is clear I have stuffed up the backup of the "post-MBR gap" data that is required for correct restore of GRUB bootloaders**.

If this is the case, to make your Lubuntu environment boot again, you need to re-installing the Linux GRUB bootloader. Some users like using the graphical boot-repair application (not  yet available in Rescuezilla). The following instructions should work from within Rescuezilla v2.0 to repair your GRUB bootloader: https://howtoubuntu.org/how-to-repair-restore-reinstall-grub-2-with-a-ubuntu-live-cd (By the way, do you have the rEFInd Boot Manager installed on your iMac? **If so, you have to be very careful you select the correct partition when re-install GRUB.**)

I will make that regression clearer in the Bug Advisory table. It will be resolved at high priority for Rescuezilla v2.1 (which is at this stage likely to be released in mid-November 2020).

As for your suggestion of adding a 'Legacy backup' menu item, I have received that request recently but I'm very hesitant to implement it. Rescuezilla v2.1 will iron out the bugs around the support for legacy _Redo Backup and Recovery_ v0.9.8-v1.0.4, _Rescuezilla_ v1.0.5-v1.0.6.1 images and Clonezilla image format support (and improve speeds). To be able to thoroughly test the application across a wide range of input images I need to focus on a limited number of features.

Again sorry for these teething issues around Rescuezilla v2.0, I hope everything will be ironed out by Rescuezilla v2.1 (scheduled for mid-November 2020)

**Comment by AE720** [comment] 2020-11-03 13:03
Thanks for the response. Here are the files from using 2.0 
[Rescuezilla.zip](https://github.com/rescuezilla/rescuezilla/files/5481311/Rescuezilla.zip)

and here are the logs 
[rescuezilla.log.20201029T202720.txt](https://github.com/rescuezilla/rescuezilla/files/5481319/rescuezilla.log.20201029T202720.txt)

Keep in mind I have very low expectations, this is a very niche situation and any help is appreciated but no pressure in any regard.

**Comment by shasheene** [comment] 2020-11-03 13:51
Thanks for the logs. I definitely want to resolve the regression bugs introduced by Rescuezilla v2.0 as soon as possible.

I will be spending some more time on Rescuezilla over the next two weeks or so. For most of Rescuezilla's existence I've maintained a 4 month release cycle, so after v2.1 is released in mid-November 2020 I hope to return to that cadence.

**Comment by shasheene** [comment] 2020-12-12 09:21
I didn't mean to close this issue. I'm not sure what the root cause of the issue is Looking at the logs nothing stands out to me.

[Rescuezilla v2.1](https://github.com/rescuezilla/rescuezilla/releases/latest) has made some improvements on both the backup and the restore side. You might have luck making a fresh backup with Rescuezilla v2.1, and testing if the restore works.

**Comment by shasheene** [comment] 2021-06-04 03:31
@AE720 can this issue be reproduced on [Rescuezilla v2.2](https://github.com/rescuezilla/rescuezilla/releases/latest)?

If so, please upload the log file (named `clonezilla-img` in the destination backup image folder).

**Comment by AE720** [comment] 2021-06-04 17:54
> @AE720 can this issue be reproduced on [Rescuezilla v2.2](https://github.com/rescuezilla/rescuezilla/releases/latest)?
> 
> If so, please upload the log file (named `clonezilla-img` in the destination backup image folder).

Thank you for checking in. I have installed the new version, made a backup with it and verified a restoration was successful. All of your hard work is appreciated immensely.

**Closed** 2021-06-04 17:55 UTC
Labels: bug
