### ISSUE TITLE
1.0.6 Slow "Shutdown" and "Reboot"

### ISSUE THREAD

**Issue by compicat** [rescuezilla/rescuezilla#87] opened 2020-06-17 23:21 UTC
Hi,

First of all, thanks for new release and features. I only realised that with this releases shutdowns and reboots are really slow. It is nearly waiting 3-4 minutes after clicking shutdown or reboot and after that waiting, it says please remove install media and press enter. It wasn't like this at previous release. Am i doing something wrong? Thanks for your efforts again.

**Comment by shasheene** [comment] 2020-06-18 02:00
During development, I did notice increased shutdown/reboot times on Rescuezilla v1.0.6 64-bit version (which is based on the Ubuntu 20.04 operating system).

I'm sorry that I didn't polish and debug that issue -- I was focused on getting v1.0.6 released after the original Redo Backup and Recovery author [returned after a 7.5 absence to create Redo Rescue](https://sourceforge.net/p/redobackup/discussion/1169663/thread/d0e37c4750/).

The Rescuezilla v1.0.6 32-bit version continues to be based on the Ubuntu 18.04 operating system, just like Rescuezilla v1.0.5.1 (which was only available in 32-bit). I have seen no issues on Rescuezilla v1.0.6 32-bit, so I recommend you use that one if you need near-instantaneous shutdown and reboot in the short term.

I will investigate the root cause and see what I can do!

**Comment by shasheene** [comment] 2020-06-25 04:13
The root cause of the slow shutdown is https://bugs.launchpad.net/ubuntu/+source/pcmanfm/+bug/1878625

I should have Rescuezilla v1.0.6.1 released within a few days!

**Closed** 2020-06-26 05:18 UTC
Labels: bug

**Comment by shasheene** [comment] 2020-06-26 06:19
Fixed in [Rescuezilla v1.0.6.1](https://github.com/rescuezilla/rescuezilla/releases/latest).

As of writing, the [root cause](https://bugs.launchpad.net/ubuntu/+source/pcmanfm/+bug/1878625) relating to the "PCManFM" file manager needs to be fixed by the Ubuntu 20.04 developers, but Rescuezilla v1.0.6.1 has improved shutdown for both the 64-bit and 32-bit version so that the slow shutdown problem is no longer an issue.

**Comment by shasheene** [comment] 2020-06-26 06:28
Fixed in [Rescuezilla v1.0.6.1](https://github.com/rescuezilla/rescuezilla/releases/latest).

As of writing, the [root cause](https://bugs.launchpad.net/ubuntu/+source/pcmanfm/+bug/1878625) relating to the "PCManFM" file manager needs to be fixed by the Ubuntu 20.04 developers, but Rescuezilla v1.0.6.1 has improved shutdown for both the 64-bit and 32-bit version so that the slow shutdown problem is no longer an issue.
