### ISSUE TITLE
Unable to use  the debian package.

### ISSUE THREAD

**Issue by njefsky** [rescuezilla/rescuezilla#217] opened 2021-05-26 10:18 UTC
I downloaded the debian package and installed it on a minimal Ubuntu 20.04.
The deb installed just fine.
The program starts just fine, asking password for elevated rights.
But I'm unable to Restore or Create Backups.
The program hangs during an unmount attempt when it tries to get the disk info.
 [Identifying disk drives]
Unmounting: /mnt/rescuzilla.image.explorer/

It would be nice if this should work. (I am creating a multiboot  test-environment, where we want to backup and restore partitions for  testing software.)  The partition with ubuntu 20.04 and rescuezilla is on same drive in multiboot with 3 Windows Partitions that we backup and restore to a seccond harddrive.

**Comment by shasheene** [comment] 2021-05-26 10:38
Hi njefsky,

I think you posted the same question on Sourceforge [recently](https://sourceforge.net/p/rescuezilla/discussion/support/thread/2a5586e1bb/) as an Anonymous user, so you didn't get an email notification when I responded:

> The deb package file doesn't get tested much outside of the Rescuezilla live environment, so for Rescuezilla v2.1.3 deb package there's a few additional things that you'll need to do an unmodified (non-Rescuezilla) Ubuntu 20.04:
> 
> Try `sudo modprobe nbd` (to fix the unmount issue) and `sudo apt-get install smartmontools` (to fix another issue that would happen during a backup operation).
> 
> Then try rerunning the application. It should now work fine!
> 
> By the way, Rescuezilla v2.2 will be released at the end of this month and has a lot of new features and improvements. I will try and remember to double-check the deb package can be installed and used on an unmodified Ubuntu system with no additional effort.

If you run `/usr/sbin/rescuezilla` from a terminal you can see the error that gets printed to the terminal. The issue is Rescuezilla was running the `nbd-client` program internally to try and ensure the Image Explorer is shutdown, but that program is not exiting.

I tested the instructions above on Lubuntu 21.04 live environment using the v2.1.3 deb package and was successfully able to do a backup/restore. Though when I rebooted and tried later (with a newer build) it didn't.

The issue is definitely caused the `nbd` module. I recommend adding it to /etc/modules so it is automatically loaded on boot up.

**Comment by shasheene** [comment] 2021-05-26 10:40
>  with 3 Windows Partitions that we backup and restore to a seccond harddrive.

Just so you're aware, you will want to ensure your Windows NTFS partitions are not hibernated (by restarting them before running Rescuezilla v2.1.3 and making any backups), because I hadn't fully implemented Clonezilla's handling of hibernated NTFS partitions (and many other Clonezilla features) until Rescuezilla v2.2 (which will be released in a few days).

**Comment by njefsky** [comment] 2021-05-26 13:07
Super thanks!
That was exactly the issue.
 I will also update to version 2.2 in a few days then.  :-)

**Closed** 2021-05-29 10:18 UTC

**Comment by shasheene** [comment] 2021-07-14 02:28
This page is understandably quite high on the Google search results, so I should mention I have created the [Installing Rescuezilla from the standalone deb package GitHub Wiki page](https://github.com/rescuezilla/rescuezilla/wiki/Installing-Rescuezilla-from-the-standalone-deb-package) so the latest instructions around installing a standalone deb package is always available.
