### ISSUE TITLE
Screen tearing on Intel GPUs, opening file manager as root from right-click menu

### ISSUE THREAD

**Issue by compicat** [rescuezilla/rescuezilla#281] opened 2021-11-06 23:30 UTC
Thanks again for great work. I wanted to give some small enhancement suggestions for v2.3

1- Screen Tearing:

If you can add intel.conf file to /etc/x11 at least for intel gpus as default at v2.3, it would be helpful. I know most of us just using rescuezilla for backups, but sometimes it is not bad to see some videos via firefox while waiting our backups :)

2- Right Click Menu "Open As Root" option for PcmanFM:

Thanks to you, we started to use uncompressed images and image explorer a lot, when we try to get some individual files, we are using "sudo pcmanfm" command via terminal a lot in order to transfer files from mounted backup image. But, it would be easier to add "open as root" function to right click menu of pcmanfm via a desktop entry at actions. It would be really helpful instead of using terminal everytime.

Thanks in advance.

**Comment by shasheene** [comment] 2021-11-07 01:39
Sure, I will implement both of these things.

**If you have a specific intel.conf file that makes sense to include then please upload it so I can include it.**

Side note: I will note here that on my _personal_ Linux desktop environment (containing an NVidia GPU), I enable the nvidia-specific "Force Full Composition Pipeline"](https://askubuntu.com/a/1170313) option when my particular desktop environment is launched. But for Rescuezilla I don't do any such configuration, so it's likely screen tearing with NVidia GPU's (when eg, watching YouTube videos) is an issue, but I haven't actually looked into it.

**Comment by compicat** [comment] 2021-11-07 01:53
Thank you for fast reply. For my situation putting below conf as 20-intel,conf to /etc/X11/xorg.conf.d is fixing tearing,

**_Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "AccelMethod" "sna"
   Option      "TearFree" "true"
EndSection_**

**Comment by shasheene** [comment] 2021-11-07 02:08
Looks good. I will double check it doesn't have any negative effect on my testing machines.

**Comment by shasheene** [comment] 2022-12-11 04:51
OK @compicat, looks like [the file I added here, `/etc/X11/xorg.conf.d/20-intel.conf`](https://github.com/rescuezilla/rescuezilla/commit/7996468daf85d73a4b98ee38736c60dc8dfe5f64) that was released with v2.3 (2021-12-24) is the cause of why Rescuezilla has recently had users complaining that Rescuezilla can't boot on Intel systems.

I'm reverting the commit, because a little bit of screen tearing is far better than not booting at all under default settings.

**Comment by compicat** [comment] 2022-12-11 06:30
> OK @compicat, looks like [the file I added here, `/etc/X11/xorg.conf.d/20-intel.conf`](https://github.com/rescuezilla/rescuezilla/commit/7996468daf85d73a4b98ee38736c60dc8dfe5f64) that was released with v2.3 (2021-12-24) is the cause of why Rescuezilla has recently had users complaining that Rescuezilla can't boot on Intel systems.
> 
> I'm reverting the commit, because a little bit of screen tearing is far better than not booting at all under default settings.

Thanks for info and finding this and sorry for causing that. It effected the releases which are newer than Focal i guess.

**Comment by shasheene** [comment] 2022-12-11 06:35
No problem -- it was on me to do further testing. And yes, it looked like it impacted releases newer than Focal.

The core screen tearing issue that you reported is still worth fixing though!

**Closed** 2022-12-12 06:07 UTC
Labels: enhancement

**Comment by shasheene** [comment] 2023-03-06 05:47
Change available from [Rescuezilla v2.4.2](https://github.com/rescuezilla/rescuezilla/releases/latest)
